# Generated by Django 3.2 on 2023-07-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Описание'),
        ),
    ]
