# Generated by Django 3.2 on 2023-06-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_component_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='maesurement_unit',
            new_name='measurement_unit',
        ),
    ]
