# Generated by Django 3.2 on 2023-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230611_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='media/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
