name: Foodgram Backend workflow

on: [push]

jobs:
  build_and_push_to_Docker_Hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploying actual version to server
    runs-on: ubuntu-latest
    needs: build_and_push_to_Docker_Hub

    steps:
    - name: Executing remote SSH commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

        script: |
          cd ${{ secrets.INFRA_DIRECTORY }}
          sudo docker pull twoalex/foodgram_backend
          sudo docker-compose stop
          sudo docker-compose up -d

  send_message:
    name: Send message to authors telegram
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен, свежая версия проекта запущена на сервере!
