# Generated by Django 3.2 on 2023-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='maesurement_unit',
            field=models.CharField(choices=[('кг', 'кг'), ('г', 'г'), ('шт', 'шт')], default='шт', max_length=3, verbose_name='Единица измерения'),
        ),
    ]
