# Generated by Django 3.2 on 2023-06-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230606_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='Component',
        ),
    ]
