# Generated by Django 3.2 on 2023-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_recipe'),
        ),
    ]
